image: ubuntu:20.04

build:
  stage: build
  script:
    - apt update
    - apt install android-tools-mkbootimg bc bison build-essential ca-certificates cpio curl flex git kmod libssl-dev libtinfo5 python2 sudo unzip wget xz-utils gzip p7zip-full -y --no-install-recommends
    - ln -sf python2.7 /usr/bin/python
    - wget https://raw.githubusercontent.com/LineageOS/android_system_tools_mkbootimg/lineage-19.1/mkbootimg.py -O /usr/bin/mkbootimg
    - ./build/build.sh
    - git clone https://github.com/draekko/AIK-Linux
    - cd AIK-Linux
    - ./unpackimg.sh ../out/boot.img
    - cp -r ../ramdisk-overlay/* ramdisk/
    - ./repackimg.sh
    - cp image-new.img ../out/boot.img
  tags:
    - x86_64
  artifacts:
    paths:
      - out/*

flashable:
  stage: deploy
  script:
    - apt update
    - apt install -y git img2simg jq sudo wget xz-utils
    - DEVICE="$(source deviceinfo && echo $deviceinfo_codename)"
    - ./build/fetch-and-prepare-latest-ota.sh "16.04/arm64/android9/devel" "$DEVICE" ota
    - mkdir -p out
    - ./build/system-image-from-ota.sh ota/ubuntu_command out
  tags:
    - x86_64
  artifacts:
    paths:
      - out/boot.img
      - out/system.img
  when: manual

devel-flashable:
  stage: deploy
  script:
    - apt update
    - apt install -y git img2simg jq sudo wget xz-utils
    - DEVICE="$(source deviceinfo && echo $deviceinfo_codename)"
    - ./build/prepare-fake-ota.sh out/device_$DEVICE.tar.xz ota
    - mkdir -p out
    - ./build/system-image-from-ota.sh ota/ubuntu_command out
    - mv out/rootfs.img out/ubuntu.img
  tags:
    - x86_64
  artifacts:
    paths:
      - out/boot.img
      - out/ubuntu.img
  when: manual

devel-flashable-gsi:
  stage: deploy
  script:
    - apt update
    - apt install -y git img2simg jq sudo wget xz-utils qemu-user-static qemu-system-arm e2fsprogs simg2img
    - wget https://ci.ubports.com/job/xenial-hybris-android9-android11-rootfs-arm64/lastSuccessfulBuild/artifact/ubuntu-touch-android9-arm64.tar.gz
    - wget https://ci.ubports.com/job/UBportsCommunityPortsJenkinsCI/job/ubports%252Fporting%252Fcommunity-ports%252Fjenkins-ci%252Fgeneric_arm64/job/main/lastSuccessfulBuild/artifact/halium_halium_arm64.tar.xz
    - tar xf halium_halium_arm64.tar.xz
    - mv system/var/lib/lxc/android/android-rootfs.img .
    - git clone https://gitlab.com/JBBgameich/halium-install
    - cd halium-install
    - git apply ../patches/halium_install.patch
    - ./halium-install -p ut -s ../ubuntu-touch-android9-arm64.tar.gz ../android-rootfs.img || true
    - cp rootfs.img android-rootfs.img ../out/
    - mount ../out/rootfs.img /mnt
    - cp -r ../overlay/system/* /mnt/
    - umount /mnt/
  tags:
    - x86_64
  artifacts:
    paths:
      - out/boot.img
      - out/android-rootfs.img
      - out/rootfs.img
